/*
====================================================================================================
-- Project: SQL Data Warehouse and Analytics
-- Script Name: 05_magnitude_analysis.sql
-- Description: This script transitions from high-level KPIs to more granular "Magnitude Analysis."
--              The purpose is to break down our key measures by different descriptive dimensions.
--              This allows us to understand the distribution and contribution of various segments
--              to the whole (e.g., how many customers come from each country, or how much revenue
--              is generated by each product category). This is a foundational step for segmentation
--              and identifying key drivers of the business.
--
-- Objectives:
--              1. To segment our customer and product bases by key attributes (country, gender, category).
--              2. To analyze the distribution of revenue and costs across different dimensions.
--              3. To identify the most significant contributors to business performance (e.g., top countries,
--                 most valuable customers).
--
-- SQL Functions Used:
--              - Aggregate Functions: SUM(), COUNT(), AVG()
--              - GROUP BY: To segment the data before applying aggregate functions.
--              - ORDER BY: To rank the results and easily identify top/bottom performers.
--              - LEFT JOIN: To combine data from fact and dimension tables.
--
-- Author: Yeswanth Sai Tirumalsetty
-- Date: 2025-07-08
====================================================================================================
*/

----------------------------------------------------------------------------------------------------
-- Analysis of Dimension Tables (Counts and Averages)
-- These queries analyze the dimension tables directly to understand the composition of our
-- customer and product catalogs.
----------------------------------------------------------------------------------------------------

-- Business Question: How many customers do we have in each country?
-- Purpose: To understand the geographical distribution of our customer base. The results are
--          ordered to quickly identify the countries with the largest customer populations.
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Business Question: What is the gender distribution of our customers?
-- Purpose: To understand the demographic makeup of our customer base.
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Business Question: How many products do we offer in each category?
-- Purpose: To understand the size and focus of our product catalog across different categories.
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Business Question: What is the average product cost within each category?
-- Purpose: To analyze the cost structure of our product offerings. This can help identify
--          high-cost vs. low-cost categories, informing pricing and sourcing strategies.
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

----------------------------------------------------------------------------------------------------
-- Analysis Combining Fact and Dimension Tables (Revenue and Sales Distribution)
-- These queries join the fact table with dimension tables to analyze performance metrics
-- across different segments.
----------------------------------------------------------------------------------------------------

-- Business Question: What is the total revenue generated by each product category?
-- Purpose: To identify which product categories are the biggest revenue drivers for the business.
--          This is critical for marketing focus, inventory planning, and strategic investment.
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Business Question: Who are our most valuable customers based on total spending?
-- Purpose: To identify our top customers (VIPs). This list is invaluable for loyalty programs,
--          personalized marketing, and customer relationship management.
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- Business Question: How many items have been sold in each country?
-- Purpose: To understand the sales volume distribution across different geographical markets.
--          This helps identify high-volume markets versus emerging ones.
SELECT
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;